// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string AddressRoad { get; set; }

    public string AddressNumber { get; set; }

    public int CityId { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<School> Schools { get; set; } = new List<School>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
    public string FullAddress => $"{AddressRoad} {AddressNumber}, {City?.PostalCode} {City?.CityName}";

}