// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string CarModel { get; set; }

    public string CarPlate { get; set; }

    public int CarCapacity { get; set; }

    public int DriverId { get; set; }

    public virtual Driver Driver { get; set; }
}