// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string DriverLicense { get; set; }

    public string DriverCpr { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public virtual User User { get; set; }
}