// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class Request
{
    public int RequestId { get; set; }

    public bool? RequestStatus { get; set; }

    public TimeOnly RequestTime { get; set; }

    public string RequestAddress { get; set; }

    public string RequestMessage { get; set; }

    public int? UserId { get; set; }

    public int TripId { get; set; }

    public virtual Trip Trip { get; set; }

    public virtual User User { get; set; }
}