// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class School
{
    public int SchoolId { get; set; }

    public string SchoolName { get; set; }

    public int AddressId { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}