// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parkeringsplads.Models;

public partial class Trip
{
    public int TripId { get; set; }

    public string FromDestination { get; set; }

    public string ToDestination { get; set; }

    public DateOnly TripDate { get; set; }

    public int TripSeats { get; set; }

    public TimeOnly TripTime { get; set; }

    public int DriverId { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}